name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Get latest mcdata commit hash
      uses: octokit/request-action@v2.x
      id: get_mcdata_hash
      with:
        route: GET /repos/Arcensoth/mcdata/branches/master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: |
        npm install
        webpack-cli -p --env.hash='${{ fromJson(steps.get_mcdata_hash.outputs.data).commit.sha }}'

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
